version: '3.7'
services:
  web:
    privileged: true
    devices:
    - "/dev/fuse:/dev/fuse"
    build: ./app
    image: apache-dso
    container_name: app-apache
    restart: always
    expose:
      - 80
    ports:
      - 80:80
      - 443:443
    volumes:
      - /mnt/app:/var/www/html/app